[phases.setup]
nixPkgs = ["python311", "libGL", "glib"]

[phases.install]
cmds = [
  "python -m venv --copies /opt/venv",
  ". /opt/venv/bin/activate && pip install --upgrade pip",
  ". /opt/venv/bin/activate && pip install 'numpy<2' --force-reinstall",
  ". /opt/venv/bin/activate && pip install tensorflow==2.15.0",
  ". /opt/venv/bin/activate && pip install deepface==0.0.83 Flask==2.3.2 flask-cors werkzeug",
  ". /opt/venv/bin/activate && pip install opencv-python-headless==4.8.1.78 --force-reinstall",
  ". /opt/venv/bin/activate && pip install 'numpy<2' --force-reinstall"
]

[start]
cmd = ". /opt/venv/bin/activate && python app.py"