[phases.setup]
nixPkgs = ["python311", "libGL", "glib"]

[phases.install]
cmds = [
  "pip install opencv-python-headless==4.8.1.78",
  "pip install deepface==0.0.83 tensorflow==2.15.0 Flask==2.3.2 flask-cors werkzeug",
  "pip uninstall -y opencv-python || true",
  "pip install opencv-python-headless==4.8.1.78 --force-reinstall"
]

[start]
cmd = "python app.py"