spring.application.name=backend
spring.datasource.url=jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:5432/postgres?prepareThreshold=0
spring.datasource.username=postgres.dbskjknzilkjrsgyysss
spring.datasource.password=AegisId@S7Major
spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=600000
spring.datasource.hikari.connection-timeout=30000
# These are the standard driver and dialect settings for PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ... other JPA settings (like ddl-auto and show-sql)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.servlet.multipart.max-file-size=25MB
spring.servlet.multipart.max-request-size=25MB

# Pinata IPFS Configuration
pinata.api-key=ceeb558b2e505363de41
pinata.secret-api-key=80669cb79bbe6b795cb9f648d7e9b80c4ce2cc3f95fde943221f5df435302cf6
pinata.dedicated-gateway=https://apricot-genetic-pig-853.mypinata.cloud/ipfs/

# Blockchain Configuration
blockchain.chain-id=80002
amoy.private.key=b7fc2a4964e2aa154cee410d80410dc226e8a219fb96c3bcec63277b74074b7d

amoy.rpc-url=https://rpc-amoy.polygon.technology/

# Ensure Hibernate handles large LOBs correctly
spring.jpa.properties.hibernate.jdbc.batch_size=50